name: Workflow Release
description: Automated release management with changesets, build validation, and GitHub releases

branding:
  icon: package
  color: blue

inputs:
  # GitHub App authentication (required)
  app-id:
    description: GitHub App ID for authentication
    required: true
  private-key:
    description: GitHub App private key (PEM format)
    required: true
  github-token:
    description: |
      GitHub token for GitHub Packages publishing (optional).
      Use this when the GitHub App doesn't have packages:write permission.
      Typically pass secrets.GITHUB_TOKEN with workflow permissions: packages: write.
    required: false
    default: ""
  skip-token-revoke:
    description: Skip token revocation in post-action (tokens expire after 1 hour anyway)
    required: false
    default: "false"

  release-branch:
    description: Release branch name
    required: false
    default: changeset-release/main
  target-branch:
    description: Target branch for PR (usually main)
    required: false
    default: main
  version-command:
    description: Custom version command (defaults to auto-detected package-manager ci:version)
    required: false
    default: ""
  pr-title-prefix:
    description: Prefix for release PR title
    required: false
    default: "chore: release"
  dry-run:
    description: Run in dry-run mode (preview only, no actual changes)
    required: false
    default: "false"

  # Custom registry authentication
  # NOTE: npm and JSR use OIDC trusted publishing - no tokens needed
  # NOTE: GitHub Packages uses the GitHub App token automatically
  custom-registries:
    description: |
      Custom registries to authenticate with the GitHub App token (one per line).
      These registries will use the same token as GitHub Packages.

      Format:
        https://registry.example.com/           # Uses GitHub App token
        https://registry.example.com/=TOKEN     # Uses explicit token (optional)

      Example:
        custom-registries: |
          https://npm.mycompany.com/

      Note: npm/JSR use OIDC trusted publishing (no configuration needed)
      Note: GitHub Packages authenticates automatically with the GitHub App token
    required: false
    default: ""

  # Optional inputs
  anthropic-api-key:
    description: Anthropic API key for Claude PR description generation
    required: false
    default: ""
  claude-review-pat:
    description: GitHub PAT for operations requiring user context
    required: false
    default: ""

outputs:
  # Token outputs (when using app-id/private-key)
  token:
    description: Generated GitHub App installation token (for use in subsequent steps)
  installation-id:
    description: GitHub App installation ID
  app-slug:
    description: GitHub App slug (URL-friendly name)

  # Phase 1: Detection outputs
  has_changes:
    description: Whether publishable changes were detected
  publishable_packages:
    description: JSON array of packages with changes

  # Phase 1: Branch outputs
  release_branch_exists:
    description: Whether the release branch exists
  release_branch_has_open_pr:
    description: Whether there's an open PR
  release_pr_number:
    description: PR number if PR exists
  release_branch_created:
    description: Whether a new release branch was created
  release_branch_updated:
    description: Whether the release branch was updated
  has_conflicts:
    description: Whether the update resulted in conflicts

  # Phase 2: Validation outputs
  linked_issues:
    description: JSON array of linked issues
  pr_description:
    description: Generated PR description
  builds_passed:
    description: Whether all builds passed
  npm_publish_ready:
    description: Whether packages are ready for NPM publish
  github_packages_ready:
    description: Whether packages are ready for GitHub Packages

  # Multi-registry publish outputs
  released_packages:
    description: JSON array of released packages with name, version, and targets
  release_type:
    description: Type of release (major, minor, or patch)
  release_tags:
    description: JSON array of created git tags
  package_count:
    description: Number of packages released
  publish_results:
    description: JSON array of publish results per package and target
  success:
    description: Whether the release was fully successful

runs:
  using: node24
  pre: dist/pre.js
  main: dist/main.js
  post: dist/post.js
